### ISSUE TITLE
Please respect the cmake's standard BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by yurivict** [iurie-sw/redkite#30]
When STATIC is replaced with SHARED it currently builds a broken shared library with a missing cairo dependency.

In the context of software packaging it is much eaqier to deal with shared libraries, so I recommend that you let the caller decide what type of library to build.

Thank you,
Yuri

**Comment by iurienistor** [comment]
I have turned off the shared build because I wanted a small library and linked only as static library. Enabling as shared library there will require to take in consideration the binary compatibility for which I made general steps in the library design, but I am not keeping this strictly, at least for now. Thus, Redkite as shared libraries for now will be useless and only will provide the ground for crashes.
